{% set goname = "git.sr.ht/~rjarry/aerc" %}
{% set version = "0.18.2" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/{{ version }}.tar.gz
    sha256: 78408b3fe7a4991a6097c961c348fb7583af52dff80cbfcd99808415cf3d7586

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - make BUILD_OPTS="-buildmode pie -compiler gc" GO_EXTRA_LDFLAGS="-extldflags '$LDFLAGS'" MANDIR=$PREFIX/man install
    - go-licenses save . --save_path ../../../../library_licenses

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cgo") }} >=1.21
    - go-licenses
    - make
    - scdoc

test:
  commands:
    - aerc -h

about:
  home: https://aerc-mail.org/
  summary: 'aerc is an email client for your terminal'
  description: |
    aerc is an email client for your terminal.

    This is a fork of the original aerc by Drew DeVault.

    A short demonstration can be found on https://aerc-mail.org/

    Join the IRC channel: #aerc on irc.libera.chat for end-user support, and development.
  license: MIT
  license_family: MIT
  license_file:
    - {{ pkg_src }}/LICENSE
    - library_licenses/
  dev_url: https://git.sr.ht/~rjarry/aerc
  doc_source_url: https://git.sr.ht/~rjarry/aerc/tree/master/item/doc/

extra:
  recipe-maintainers:
    - blmaier
